import React from 'react';

const Ciudades =  ()  =>   {
let ciudadesNull    =   [];
localStorage.setItem('ListaCiudadesCol',JSON.stringify(ciudadesNull));
let Ciudades = [
    {id:1,departamento_id:1,ciudad:'MEDELLIN'},
    {id:2,departamento_id:1,ciudad:'ABEJORRAL'},
    {id:3,departamento_id:1,ciudad:'ABRIAQUI'},
    {id:4,departamento_id:1,ciudad:'ALEJANDRIA'},
    {id:5,departamento_id:1,ciudad:'AMAGA'},
    {id:6,departamento_id:1,ciudad:'AMALFI'},
    {id:7,departamento_id:1,ciudad:'ANDES'},
    {id:8,departamento_id:1,ciudad:'ANGELOPOLIS'},
    {id:9,departamento_id:1,ciudad:'ANGOSTURA'},
    {id:10,departamento_id:1,ciudad:'ANORI'},
    {id:11,departamento_id:1,ciudad:'ANTIOQUIA'},
    {id:12,departamento_id:1,ciudad:'ANZA'},
    {id:13,departamento_id:1,ciudad:'APARTADO'},
    {id:14,departamento_id:1,ciudad:'ARBOLETES'},
    {id:15,departamento_id:1,ciudad:'ARGELIA'},
    {id:16,departamento_id:1,ciudad:'ARMENIA'},
    {id:17,departamento_id:1,ciudad:'BARBOSA'},
    {id:18,departamento_id:1,ciudad:'BELMIRA'},
    {id:19,departamento_id:1,ciudad:'BELLO'},
    {id:20,departamento_id:1,ciudad:'BETANIA'},
    {id:21,departamento_id:1,ciudad:'BETULIA'},
    {id:22,departamento_id:1,ciudad:'BOLIVAR'},
    {id:23,departamento_id:1,ciudad:'BRICEÑO'},
    {id:24,departamento_id:1,ciudad:'BURITICA'},
    {id:25,departamento_id:1,ciudad:'CACERES'},
    {id:26,departamento_id:1,ciudad:'CAICEDO'},
    {id:27,departamento_id:1,ciudad:'CALDAS'},
    {id:28,departamento_id:1,ciudad:'CAMPAMENTO'},
    {id:29,departamento_id:1,ciudad:'CAÑASGORDAS'},
    {id:30,departamento_id:1,ciudad:'CARACOLI'},
    {id:31,departamento_id:1,ciudad:'CARAMANTA'},
    {id:32,departamento_id:1,ciudad:'CAREPA'},
    {id:33,departamento_id:1,ciudad:'CARMEN DE VIBORAL'},
    {id:34,departamento_id:1,ciudad:'CAROLINA'},
    {id:35,departamento_id:1,ciudad:'CAUCASIA'},
    {id:36,departamento_id:1,ciudad:'CHIGORODO'},
    {id:37,departamento_id:1,ciudad:'CISNEROS'},
    {id:38,departamento_id:1,ciudad:'COCORNA'},
    {id:39,departamento_id:1,ciudad:'CONCEPCION'},
    {id:40,departamento_id:1,ciudad:'CONCORDIA'},
    {id:41,departamento_id:1,ciudad:'COPACABANA'},
    {id:42,departamento_id:1,ciudad:'DABEIBA'},
    {id:43,departamento_id:1,ciudad:'DON MATIAS'},
    {id:44,departamento_id:1,ciudad:'EBEJICO'},
    {id:45,departamento_id:1,ciudad:'EL BAGRE'},
    {id:46,departamento_id:1,ciudad:'ENTRERRIOS'},
    {id:47,departamento_id:1,ciudad:'ENVIGADO'},
    {id:48,departamento_id:1,ciudad:'FREDONIA'},
    {id:49,departamento_id:1,ciudad:'FRONTINO'},
    {id:50,departamento_id:1,ciudad:'GIRALDO'},
    {id:51,departamento_id:1,ciudad:'GIRARDOTA'},
    {id:52,departamento_id:1,ciudad:'GOMEZ PLATA'},
    {id:53,departamento_id:1,ciudad:'GRANADA'},
    {id:54,departamento_id:1,ciudad:'GUADALUPE'},
    {id:55,departamento_id:1,ciudad:'GUARNE'},
    {id:56,departamento_id:1,ciudad:'GUATAPE'},
    {id:57,departamento_id:1,ciudad:'HELICONIA'},
    {id:58,departamento_id:1,ciudad:'HISPANIA'},
    {id:59,departamento_id:1,ciudad:'ITAGUI'},
    {id:60,departamento_id:1,ciudad:'ITUANGO'},
    {id:61,departamento_id:1,ciudad:'JARDIN'},
    {id:62,departamento_id:1,ciudad:'JERICO'},
    {id:63,departamento_id:1,ciudad:'LA CEJA'},
    {id:64,departamento_id:1,ciudad:'LA ESTRELLA'},
    {id:65,departamento_id:1,ciudad:'LA PINTADA'},
    {id:66,departamento_id:1,ciudad:'LA UNION'},
    {id:67,departamento_id:1,ciudad:'LIBORINA'},
    {id:68,departamento_id:1,ciudad:'MACEO'},
    {id:69,departamento_id:1,ciudad:'MARINILLA'},
    {id:70,departamento_id:1,ciudad:'MONTEBELLO'},
    {id:71,departamento_id:1,ciudad:'MURINDO'},
    {id:72,departamento_id:1,ciudad:'MUTATA'},
    {id:73,departamento_id:1,ciudad:'NARIÑO'},
    {id:74,departamento_id:1,ciudad:'NECOCLI'},
    {id:75,departamento_id:1,ciudad:'NECHI'},
    {id:76,departamento_id:1,ciudad:'OLAYA'},
    {id:77,departamento_id:1,ciudad:'PEÑOL'},
    {id:78,departamento_id:1,ciudad:'PEQUE'},
    {id:79,departamento_id:1,ciudad:'PUEBLORRICO'},
    {id:80,departamento_id:1,ciudad:'PUERTO BERRIO'},
    {id:81,departamento_id:1,ciudad:'PUERTO NARE (LA MAGDALENA'},
    {id:82,departamento_id:1,ciudad:'PUERTO TRIUNFO'},
    {id:83,departamento_id:1,ciudad:'REMEDIOS'},
    {id:84,departamento_id:1,ciudad:'RETIRO'},
    {id:85,departamento_id:1,ciudad:'RIONEGRO'},
    {id:86,departamento_id:1,ciudad:'SABANALARGA'},
    {id:87,departamento_id:1,ciudad:'SABANETA'},
    {id:88,departamento_id:1,ciudad:'SALGAR'},
    {id:89,departamento_id:1,ciudad:'SAN ANDRES'},
    {id:90,departamento_id:1,ciudad:'SAN CARLOS'},
    {id:91,departamento_id:1,ciudad:'SAN FRANCISCO'},
    {id:92,departamento_id:1,ciudad:'SAN JERONIMO'},
    {id:93,departamento_id:1,ciudad:'SAN JOSE DE LA MONTAÑA'},
    {id:94,departamento_id:1,ciudad:'SAN JUAN DE URABA'},
    {id:95,departamento_id:1,ciudad:'SAN LUIS'},
    {id:96,departamento_id:1,ciudad:'SAN PEDRO'},
    {id:97,departamento_id:1,ciudad:'SAN PEDRO DE URABA'},
    {id:98,departamento_id:1,ciudad:'SAN RAFAEL'},
    {id:99,departamento_id:1,ciudad:'SAN ROQUE'},
    {id:100,departamento_id:1,ciudad:'SAN VICENTE'},
    {id:101,departamento_id:1,ciudad:'SANTA BARBARA'},
    {id:102,departamento_id:1,ciudad:'SANTA ROSA DE OSOS'},
    {id:103,departamento_id:1,ciudad:'SANTO DOMINGO'},
    {id:104,departamento_id:1,ciudad:'SANTUARIO'},
    {id:105,departamento_id:1,ciudad:'SEGOVIA'},
    {id:106,departamento_id:1,ciudad:'SONSON'},
    {id:107,departamento_id:1,ciudad:'SOPETRAN'},
    {id:108,departamento_id:1,ciudad:'TAMESIS'},
    {id:109,departamento_id:1,ciudad:'TARAZA'},
    {id:110,departamento_id:1,ciudad:'TARSO'},
    {id:111,departamento_id:1,ciudad:'TITIRIBI'},
    {id:112,departamento_id:1,ciudad:'TOLEDO'},
    {id:113,departamento_id:1,ciudad:'TURBO'},
    {id:114,departamento_id:1,ciudad:'URAMITA'},
    {id:115,departamento_id:1,ciudad:'URRAO'},
    {id:116,departamento_id:1,ciudad:'VALDIVIA'},
    {id:117,departamento_id:1,ciudad:'VALPARAISO'},
    {id:118,departamento_id:1,ciudad:'VEGACHI'},
    {id:119,departamento_id:1,ciudad:'VENECIA'},
    {id:120,departamento_id:1,ciudad:'VIGIA DEL FUERTE'},
    {id:121,departamento_id:1,ciudad:'YALI'},
    {id:122,departamento_id:1,ciudad:'YARUMAL'},
    {id:123,departamento_id:1,ciudad:'YOLOMBO'},
    {id:124,departamento_id:1,ciudad:'YONDO'},
    {id:125,departamento_id:1,ciudad:'ZARAGOZA'},
    {id:126,departamento_id:2,ciudad:'BARRANQUILLA (DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA'},
    {id:127,departamento_id:2,ciudad:'BARANOA'},
    {id:128,departamento_id:2,ciudad:'CAMPO DE LA CRUZ'},
    {id:129,departamento_id:2,ciudad:'CANDELARIA'},
    {id:130,departamento_id:2,ciudad:'GALAPA'},
    {id:131,departamento_id:2,ciudad:'JUAN DE ACOSTA'},
    {id:132,departamento_id:2,ciudad:'LURUACO'},
    {id:133,departamento_id:2,ciudad:'MALAMBO'},
    {id:134,departamento_id:2,ciudad:'MANATI'},
    {id:135,departamento_id:2,ciudad:'PALMAR DE VARELA'},
    {id:136,departamento_id:2,ciudad:'PIOJO'},
    {id:137,departamento_id:2,ciudad:'POLO NUEVO'},
    {id:138,departamento_id:2,ciudad:'PONEDERA'},
    {id:139,departamento_id:2,ciudad:'PUERTO COLOMBIA'},
    {id:140,departamento_id:2,ciudad:'REPELON'},
    {id:141,departamento_id:2,ciudad:'SABANAGRANDE'},
    {id:142,departamento_id:2,ciudad:'SABANALARGA'},
    {id:143,departamento_id:2,ciudad:'SANTA LUCIA'},
    {id:144,departamento_id:2,ciudad:'SANTO TOMAS'},
    {id:145,departamento_id:2,ciudad:'SOLEDAD'},
    {id:146,departamento_id:2,ciudad:'SUAN'},
    {id:147,departamento_id:2,ciudad:'TUBARA'},
    {id:148,departamento_id:2,ciudad:'USIACURI'},
    {id:149,departamento_id:3,ciudad:'Santa Fe de Bogotá'},
    {id:150,departamento_id:3,ciudad:'USAQUEN'},
    {id:151,departamento_id:3,ciudad:'CHAPINERO'},
    {id:152,departamento_id:3,ciudad:'SANTA FE'},
    {id:153,departamento_id:3,ciudad:'SAN CRISTOBAL'},
    {id:154,departamento_id:3,ciudad:'USME'},
    {id:155,departamento_id:3,ciudad:'TUNJUELITO'},
    {id:156,departamento_id:3,ciudad:'BOSA'},
    {id:157,departamento_id:3,ciudad:'KENNEDY'},
    {id:158,departamento_id:3,ciudad:'FONTIBON'},
    {id:159,departamento_id:3,ciudad:'ENGATIVA'},
    {id:160,departamento_id:3,ciudad:'SUBA'},
    {id:161,departamento_id:3,ciudad:'BARRIOS UNIDOS'},
    {id:162,departamento_id:3,ciudad:'TEUSAQUILLO'},
    {id:163,departamento_id:3,ciudad:'MARTIRES'},
    {id:164,departamento_id:3,ciudad:'ANTONIO NARIÑO'},
    {id:165,departamento_id:3,ciudad:'PUENTE ARANDA'},
    {id:166,departamento_id:3,ciudad:'CANDELARIA'},
    {id:167,departamento_id:3,ciudad:'RAFAEL URIBE'},
    {id:168,departamento_id:3,ciudad:'CIUDAD BOLIVAR'},
    {id:169,departamento_id:3,ciudad:'SUMAPAZ'},
    {id:170,departamento_id:4,ciudad:'CARTAGENA (DISTRITO TURISTICO Y CULTURAL DE CARTAGENA'},
    {id:171,departamento_id:4,ciudad:'ACHI'},
    {id:172,departamento_id:4,ciudad:'ALTOS DEL ROSARIO'},
    {id:173,departamento_id:4,ciudad:'ARENAL'},
    {id:174,departamento_id:4,ciudad:'ARJONA'},
    {id:175,departamento_id:4,ciudad:'ARROYOHONDO'},
    {id:176,departamento_id:4,ciudad:'BARRANCO DE LOBA'},
    {id:177,departamento_id:4,ciudad:'CALAMAR'},
    {id:178,departamento_id:4,ciudad:'CANTAGALLO'},
    {id:179,departamento_id:4,ciudad:'CICUCO'},
    {id:180,departamento_id:4,ciudad:'CORDOBA'},
    {id:181,departamento_id:4,ciudad:'CLEMENCIA'},
    {id:182,departamento_id:4,ciudad:'EL CARMEN DE BOLIVAR'},
    {id:183,departamento_id:4,ciudad:'EL GUAMO'},
    {id:184,departamento_id:4,ciudad:'EL PEÑON'},
    {id:185,departamento_id:4,ciudad:'HATILLO DE LOBA'},
    {id:186,departamento_id:4,ciudad:'MAGANGUE'},
    {id:187,departamento_id:4,ciudad:'MAHATES'},
    {id:188,departamento_id:4,ciudad:'MARGARITA'},
    {id:189,departamento_id:4,ciudad:'MARIA LA BAJA'},
    {id:190,departamento_id:4,ciudad:'MONTECRISTO'},
    {id:191,departamento_id:4,ciudad:'MOMPOS'},
    {id:192,departamento_id:4,ciudad:'MORALES'},
    {id:193,departamento_id:4,ciudad:'PINILLOS'},
    {id:194,departamento_id:4,ciudad:'REGIDOR'},
    {id:195,departamento_id:4,ciudad:'RIO VIEJO'},
    {id:196,departamento_id:4,ciudad:'SAN CRISTOBAL'},
    {id:197,departamento_id:4,ciudad:'SAN ESTANISLAO'},
    {id:198,departamento_id:4,ciudad:'SAN FERNANDO'},
    {id:199,departamento_id:4,ciudad:'SAN JACINTO'},
    {id:200,departamento_id:4,ciudad:'SAN JACINTO DEL CAUCA'},
    {id:201,departamento_id:4,ciudad:'SAN JUAN NEPOMUCENO'},
    {id:202,departamento_id:4,ciudad:'SAN MARTIN DE LOBA'},
    {id:203,departamento_id:4,ciudad:'SAN PABLO'},
    {id:204,departamento_id:4,ciudad:'SANTA CATALINA'},
    {id:205,departamento_id:4,ciudad:'SANTA ROSA'},
    {id:206,departamento_id:4,ciudad:'SANTA ROSA DEL SUR'},
    {id:207,departamento_id:4,ciudad:'SIMITI'},
    {id:208,departamento_id:4,ciudad:'SOPLAVIENTO'},
    {id:209,departamento_id:4,ciudad:'TALAIGUA NUEVO'},
    {id:210,departamento_id:4,ciudad:'TIQUISIO (PUERTO RICO'},
    {id:211,departamento_id:4,ciudad:'TURBACO'},
    {id:212,departamento_id:4,ciudad:'TURBANA'},
    {id:213,departamento_id:4,ciudad:'VILLANUEVA'},
    {id:214,departamento_id:4,ciudad:'ZAMBRANO'},
    {id:215,departamento_id:5,ciudad:'TUNJA'},
    {id:216,departamento_id:5,ciudad:'ALMEIDA'},
    {id:217,departamento_id:5,ciudad:'AQUITANIA'},
    {id:218,departamento_id:5,ciudad:'ARCABUCO'},
    {id:219,departamento_id:5,ciudad:'BELEN'},
    {id:220,departamento_id:5,ciudad:'BERBEO'},
    {id:221,departamento_id:5,ciudad:'BETEITIVA'},
    {id:222,departamento_id:5,ciudad:'BOAVITA'},
    {id:223,departamento_id:5,ciudad:'BOYACA'},
    {id:224,departamento_id:5,ciudad:'BRICEÑO'},
    {id:225,departamento_id:5,ciudad:'BUENAVISTA'},
    {id:226,departamento_id:5,ciudad:'BUSBANZA'},
    {id:227,departamento_id:5,ciudad:'CALDAS'},
    {id:228,departamento_id:5,ciudad:'CAMPOHERMOSO'},
    {id:229,departamento_id:5,ciudad:'CERINZA'},
    {id:230,departamento_id:5,ciudad:'CHINAVITA'},
    {id:231,departamento_id:5,ciudad:'CHIQUINQUIRA'},
    {id:232,departamento_id:5,ciudad:'CHISCAS'},
    {id:233,departamento_id:5,ciudad:'CHITA'},
    {id:234,departamento_id:5,ciudad:'CHITARAQUE'},
    {id:235,departamento_id:5,ciudad:'CHIVATA'},
    {id:236,departamento_id:5,ciudad:'CIENEGA'},
    {id:237,departamento_id:5,ciudad:'COMBITA'},
    {id:238,departamento_id:5,ciudad:'COPER'},
    {id:239,departamento_id:5,ciudad:'CORRALES'},
    {id:240,departamento_id:5,ciudad:'COVARACHIA'},
    {id:241,departamento_id:5,ciudad:'CUBARA'},
    {id:242,departamento_id:5,ciudad:'CUCAITA'},
    {id:243,departamento_id:5,ciudad:'CUITIVA'},
    {id:244,departamento_id:5,ciudad:'CHIQUIZA'},
    {id:245,departamento_id:5,ciudad:'CHIVOR'},
    {id:246,departamento_id:5,ciudad:'DUITAMA'},
    {id:247,departamento_id:5,ciudad:'EL COCUY'},
    {id:248,departamento_id:5,ciudad:'EL ESPINO'},
    {id:249,departamento_id:5,ciudad:'FIRAVITOBA'},
    {id:250,departamento_id:5,ciudad:'FLORESTA'},
    {id:251,departamento_id:5,ciudad:'GACHANTIVA'},
    {id:252,departamento_id:5,ciudad:'GAMEZA'},
    {id:253,departamento_id:5,ciudad:'GARAGOA'},
    {id:254,departamento_id:5,ciudad:'GUACAMAYAS'},
    {id:255,departamento_id:5,ciudad:'GUATEQUE'},
    {id:256,departamento_id:5,ciudad:'GUAYATA'},
    {id:257,departamento_id:5,ciudad:'GUICAN'},
    {id:258,departamento_id:5,ciudad:'IZA'},
    {id:259,departamento_id:5,ciudad:'JENESANO'},
    {id:260,departamento_id:5,ciudad:'JERICO'},
    {id:261,departamento_id:5,ciudad:'LABRANZAGRANDE'},
    {id:262,departamento_id:5,ciudad:'LA CAPILLA'},
    {id:263,departamento_id:5,ciudad:'LA VICTORIA'},
    {id:264,departamento_id:5,ciudad:'LA UVITA'},
    {id:265,departamento_id:5,ciudad:'VILLA DE LEIVA'},
    {id:266,departamento_id:5,ciudad:'MACANAL'},
    {id:267,departamento_id:5,ciudad:'MARIPI'},
    {id:268,departamento_id:5,ciudad:'MIRAFLORES'},
    {id:269,departamento_id:5,ciudad:'MONGUA'},
    {id:270,departamento_id:5,ciudad:'MONGUI'},
    {id:271,departamento_id:5,ciudad:'MONIQUIRA'},
    {id:272,departamento_id:5,ciudad:'MOTAVITA'},
    {id:273,departamento_id:5,ciudad:'MUZO'},
    {id:274,departamento_id:5,ciudad:'NOBSA'},
    {id:275,departamento_id:5,ciudad:'NUEVO COLON'},
    {id:276,departamento_id:5,ciudad:'OICATA'},
    {id:277,departamento_id:5,ciudad:'OTANCHE'},
    {id:278,departamento_id:5,ciudad:'PACHAVITA'},
    {id:279,departamento_id:5,ciudad:'PAEZ'},
    {id:280,departamento_id:5,ciudad:'PAIPA'},
    {id:281,departamento_id:5,ciudad:'PAJARITO'},
    {id:282,departamento_id:5,ciudad:'PANQUEBA'},
    {id:283,departamento_id:5,ciudad:'PAUNA'},
    {id:284,departamento_id:5,ciudad:'PAYA'},
    {id:285,departamento_id:5,ciudad:'PAZ DEL RIO'},
    {id:286,departamento_id:5,ciudad:'PESCA'},
    {id:287,departamento_id:5,ciudad:'PISBA'},
    {id:288,departamento_id:5,ciudad:'PUERTO BOYACA'},
    {id:289,departamento_id:5,ciudad:'QUIPAMA'},
    {id:290,departamento_id:5,ciudad:'RAMIRIQUI'},
    {id:291,departamento_id:5,ciudad:'RAQUIRA'},
    {id:292,departamento_id:5,ciudad:'RONDON'},
    {id:293,departamento_id:5,ciudad:'SABOYA'},
    {id:294,departamento_id:5,ciudad:'SACHICA'},
    {id:295,departamento_id:5,ciudad:'SAMACA'},
    {id:296,departamento_id:5,ciudad:'SAN EDUARDO'},
    {id:297,departamento_id:5,ciudad:'SAN JOSE DE PARE'},
    {id:298,departamento_id:5,ciudad:'SAN LUIS DE GACENO'},
    {id:299,departamento_id:5,ciudad:'SAN MATEO'},
    {id:300,departamento_id:5,ciudad:'SAN MIGUEL DE SEMA'},
    {id:301,departamento_id:5,ciudad:'SAN PABLO DE BORBUR'},
    {id:302,departamento_id:5,ciudad:'SANTANA'},
    {id:303,departamento_id:5,ciudad:'SANTA MARIA'},
    {id:304,departamento_id:5,ciudad:'SANTA ROSA DE VITERBO'},
    {id:305,departamento_id:5,ciudad:'SANTA SOFIA'},
    {id:306,departamento_id:5,ciudad:'SATIVANORTE'},
    {id:307,departamento_id:5,ciudad:'SATIVASUR'},
    {id:308,departamento_id:5,ciudad:'SIACHOQUE'},
    {id:309,departamento_id:5,ciudad:'SOATA'},
    {id:310,departamento_id:5,ciudad:'SOCOTA'},
    {id:311,departamento_id:5,ciudad:'SOCHA'},
    {id:312,departamento_id:5,ciudad:'SOGAMOSO'},
    {id:313,departamento_id:5,ciudad:'SOMONDOCO'},
    {id:314,departamento_id:5,ciudad:'SORA'},
    {id:315,departamento_id:5,ciudad:'SOTAQUIRA'},
    {id:316,departamento_id:5,ciudad:'SORACA'},
    {id:317,departamento_id:5,ciudad:'SUSACON'},
    {id:318,departamento_id:5,ciudad:'SUTAMARCHAN'},
    {id:319,departamento_id:5,ciudad:'SUTATENZA'},
    {id:320,departamento_id:5,ciudad:'TASCO'},
    {id:321,departamento_id:5,ciudad:'TENZA'},
    {id:322,departamento_id:5,ciudad:'TIBANA'},
    {id:323,departamento_id:5,ciudad:'TIBASOSA'},
    {id:324,departamento_id:5,ciudad:'TINJACA'},
    {id:325,departamento_id:5,ciudad:'TIPACOQUE'},
    {id:326,departamento_id:5,ciudad:'TOCA'},
    {id:327,departamento_id:5,ciudad:'TOGUI'},
    {id:328,departamento_id:5,ciudad:'TOPAGA'},
    {id:329,departamento_id:5,ciudad:'TOTA'},
    {id:330,departamento_id:5,ciudad:'TUNUNGUA'},
    {id:331,departamento_id:5,ciudad:'TURMEQUE'},
    {id:332,departamento_id:5,ciudad:'TUTA'},
    {id:333,departamento_id:5,ciudad:'TUTASA'},
    {id:334,departamento_id:5,ciudad:'UMBITA'},
    {id:335,departamento_id:5,ciudad:'VENTAQUEMADA'},
    {id:336,departamento_id:5,ciudad:'VIRACACHA'},
    {id:337,departamento_id:5,ciudad:'ZETAQUIRA'},
    {id:338,departamento_id:6,ciudad:'MANIZALES'},
    {id:339,departamento_id:6,ciudad:'AGUADAS'},
    {id:340,departamento_id:6,ciudad:'ANSERMA'},
    {id:341,departamento_id:6,ciudad:'ARANZAZU'},
    {id:342,departamento_id:6,ciudad:'BELALCAZAR'},
    {id:343,departamento_id:6,ciudad:'CHINCHINA'},
    {id:344,departamento_id:6,ciudad:'FILADELFIA'},
    {id:345,departamento_id:6,ciudad:'LA DORADA'},
    {id:346,departamento_id:6,ciudad:'LA MERCED'},
    {id:347,departamento_id:6,ciudad:'MANZANARES'},
    {id:348,departamento_id:6,ciudad:'MARMATO'},
    {id:349,departamento_id:6,ciudad:'MARQUETALIA'},
    {id:350,departamento_id:6,ciudad:'MARULANDA'},
    {id:351,departamento_id:6,ciudad:'NEIRA'},
    {id:352,departamento_id:6,ciudad:'NORCASIA'},
    {id:353,departamento_id:6,ciudad:'PACORA'},
    {id:354,departamento_id:6,ciudad:'PALESTINA'},
    {id:355,departamento_id:6,ciudad:'PENSILVANIA'},
    {id:356,departamento_id:6,ciudad:'RIOSUCIO'},
    {id:357,departamento_id:6,ciudad:'RISARALDA'},
    {id:358,departamento_id:6,ciudad:'SALAMINA'},
    {id:359,departamento_id:6,ciudad:'SAMANA'},
    {id:360,departamento_id:6,ciudad:'SAN JOSE'},
    {id:361,departamento_id:6,ciudad:'SUPIA'},
    {id:362,departamento_id:6,ciudad:'VICTORIA'},
    {id:363,departamento_id:6,ciudad:'VILLAMARIA'},
    {id:364,departamento_id:6,ciudad:'VITERBO'},
    {id:365,departamento_id:7,ciudad:'FLORENCIA'},
    {id:366,departamento_id:7,ciudad:'ALBANIA'},
    {id:367,departamento_id:7,ciudad:'BELEN DE LOS ANDAQUIES'},
    {id:368,departamento_id:7,ciudad:'CARTAGENA DEL CHAIRA'},
    {id:369,departamento_id:7,ciudad:'CURILLO'},
    {id:370,departamento_id:7,ciudad:'EL DONCELLO'},
    {id:371,departamento_id:7,ciudad:'EL PAUJIL'},
    {id:372,departamento_id:7,ciudad:'LA MONTAÑITA'},
    {id:373,departamento_id:7,ciudad:'MILAN'},
    {id:374,departamento_id:7,ciudad:'MORELIA'},
    {id:375,departamento_id:7,ciudad:'PUERTO RICO'},
    {id:376,departamento_id:7,ciudad:'SAN JOSE DE FRAGUA'},
    {id:377,departamento_id:7,ciudad:'SAN VICENTE DEL CAGUAN'},
    {id:378,departamento_id:7,ciudad:'SOLANO'},
    {id:379,departamento_id:7,ciudad:'SOLITA'},
    {id:380,departamento_id:7,ciudad:'VALPARAISO'},
    {id:381,departamento_id:8,ciudad:'POPAYAN'},
    {id:382,departamento_id:8,ciudad:'ALMAGUER'},
    {id:383,departamento_id:8,ciudad:'ARGELIA'},
    {id:384,departamento_id:8,ciudad:'BALBOA'},
    {id:385,departamento_id:8,ciudad:'BOLIVAR'},
    {id:386,departamento_id:8,ciudad:'BUENOS AIRES'},
    {id:387,departamento_id:8,ciudad:'CAJIBIO'},
    {id:388,departamento_id:8,ciudad:'CALDONO'},
    {id:389,departamento_id:8,ciudad:'CALOTO'},
    {id:390,departamento_id:8,ciudad:'CORINTO'},
    {id:391,departamento_id:8,ciudad:'EL TAMBO'},
    {id:392,departamento_id:8,ciudad:'FLORENCIA'},
    {id:393,departamento_id:8,ciudad:'GUAPI'},
    {id:394,departamento_id:8,ciudad:'INZA'},
    {id:395,departamento_id:8,ciudad:'JAMBALO'},
    {id:396,departamento_id:8,ciudad:'LA SIERRA'},
    {id:397,departamento_id:8,ciudad:'LA VEGA'},
    {id:398,departamento_id:8,ciudad:'LOPEZ (MICAY'},
    {id:399,departamento_id:8,ciudad:'MERCADERES'},
    {id:400,departamento_id:8,ciudad:'MIRANDA'},
    {id:401,departamento_id:8,ciudad:'MORALES'},
    {id:402,departamento_id:8,ciudad:'PADILLA'},
    {id:403,departamento_id:8,ciudad:'PAEZ (BELALCAZAR'},
    {id:404,departamento_id:8,ciudad:'PATIA (EL BORDO'},
    {id:405,departamento_id:8,ciudad:'PIAMONTE'},
    {id:406,departamento_id:8,ciudad:'PIENDAMO'},
    {id:407,departamento_id:8,ciudad:'PUERTO TEJADA'},
    {id:408,departamento_id:8,ciudad:'PURACE (COCONUCO'},
    {id:409,departamento_id:8,ciudad:'ROSAS'},
    {id:410,departamento_id:8,ciudad:'SAN SEBASTIAN'},
    {id:411,departamento_id:8,ciudad:'SANTANDER DE QUILICHAO'},
    {id:412,departamento_id:8,ciudad:'SANTA ROSA'},
    {id:413,departamento_id:8,ciudad:'SILVIA'},
    {id:414,departamento_id:8,ciudad:'SOTARA (PAISPAMBA'},
    {id:415,departamento_id:8,ciudad:'SUAREZ'},
    {id:416,departamento_id:8,ciudad:'TIMBIO'},
    {id:417,departamento_id:8,ciudad:'TIMBIQUI'},
    {id:418,departamento_id:8,ciudad:'TORIBIO'},
    {id:419,departamento_id:8,ciudad:'TOTORO'},
    {id:420,departamento_id:8,ciudad:'VILLARICA'},
    {id:421,departamento_id:9,ciudad:'VALLEDUPAR'},
    {id:422,departamento_id:9,ciudad:'AGUACHICA'},
    {id:423,departamento_id:9,ciudad:'AGUSTIN CODAZZI'},
    {id:424,departamento_id:9,ciudad:'ASTREA'},
    {id:425,departamento_id:9,ciudad:'BECERRIL'},
    {id:426,departamento_id:9,ciudad:'BOSCONIA'},
    {id:427,departamento_id:9,ciudad:'CHIMICHAGUA'},
    {id:428,departamento_id:9,ciudad:'CHIRIGUANA'},
    {id:429,departamento_id:9,ciudad:'CURUMANI'},
    {id:430,departamento_id:9,ciudad:'EL COPEY'},
    {id:431,departamento_id:9,ciudad:'EL PASO'},
    {id:432,departamento_id:9,ciudad:'GAMARRA'},
    {id:433,departamento_id:9,ciudad:'GONZALEZ'},
    {id:434,departamento_id:9,ciudad:'LA GLORIA'},
    {id:435,departamento_id:9,ciudad:'LA JAGUA IBIRICO'},
    {id:436,departamento_id:9,ciudad:'MANAURE (BALCON DEL CESAR'},
    {id:437,departamento_id:9,ciudad:'PAILITAS'},
    {id:438,departamento_id:9,ciudad:'PELAYA'},
    {id:439,departamento_id:9,ciudad:'PUEBLO BELLO'},
    {id:440,departamento_id:9,ciudad:'RIO DE ORO'},
    {id:441,departamento_id:9,ciudad:'LA PAZ (ROBLES'},
    {id:442,departamento_id:9,ciudad:'SAN ALBERTO'},
    {id:443,departamento_id:9,ciudad:'SAN DIEGO'},
    {id:444,departamento_id:9,ciudad:'SAN MARTIN'},
    {id:445,departamento_id:9,ciudad:'TAMALAMEQUE'},
    {id:446,departamento_id:10,ciudad:'MONTERIA'},
    {id:447,departamento_id:10,ciudad:'AYAPEL'},
    {id:448,departamento_id:10,ciudad:'BUENAVISTA'},
    {id:449,departamento_id:10,ciudad:'CANALETE'},
    {id:450,departamento_id:10,ciudad:'CERETE'},
    {id:451,departamento_id:10,ciudad:'CHIMA'},
    {id:452,departamento_id:10,ciudad:'CHINU'},
    {id:453,departamento_id:10,ciudad:'CIENAGA DE ORO'},
    {id:454,departamento_id:10,ciudad:'COTORRA'},
    {id:455,departamento_id:10,ciudad:'LA APARTADA'},
    {id:456,departamento_id:10,ciudad:'LORICA'},
    {id:457,departamento_id:10,ciudad:'LOS CORDOBAS'},
    {id:458,departamento_id:10,ciudad:'MOMIL'},
    {id:459,departamento_id:10,ciudad:'MONTELIBANO'},
    {id:460,departamento_id:10,ciudad:'MOÑITOS'},
    {id:461,departamento_id:10,ciudad:'PLANETA RICA'},
    {id:462,departamento_id:10,ciudad:'PUEBLO NUEVO'},
    {id:463,departamento_id:10,ciudad:'PUERTO ESCONDIDO'},
    {id:464,departamento_id:10,ciudad:'PUERTO LIBERTADOR'},
    {id:465,departamento_id:10,ciudad:'PURISIMA'},
    {id:466,departamento_id:10,ciudad:'SAHAGUN'},
    {id:467,departamento_id:10,ciudad:'SAN ANDRES SOTAVENTO'},
    {id:468,departamento_id:10,ciudad:'SAN ANTERO'},
    {id:469,departamento_id:10,ciudad:'SAN BERNARDO DEL VIENTO'},
    {id:470,departamento_id:10,ciudad:'SAN CARLOS'},
    {id:471,departamento_id:10,ciudad:'SAN PELAYO'},
    {id:472,departamento_id:10,ciudad:'TIERRALTA'},
    {id:473,departamento_id:10,ciudad:'VALENCIA'},
    {id:474,departamento_id:11,ciudad:'AGUA DE DIOS'},
    {id:475,departamento_id:11,ciudad:'ALBAN'},
    {id:476,departamento_id:11,ciudad:'ANAPOIMA'},
    {id:477,departamento_id:11,ciudad:'ANOLAIMA'},
    {id:478,departamento_id:11,ciudad:'ARBELAEZ'},
    {id:479,departamento_id:11,ciudad:'BELTRAN'},
    {id:480,departamento_id:11,ciudad:'BITUIMA'},
    {id:481,departamento_id:11,ciudad:'BOJACA'},
    {id:482,departamento_id:11,ciudad:'CABRERA'},
    {id:483,departamento_id:11,ciudad:'CACHIPAY'},
    {id:484,departamento_id:11,ciudad:'CAJICA'},
    {id:485,departamento_id:11,ciudad:'CAPARRAPI'},
    {id:486,departamento_id:11,ciudad:'CAQUEZA'},
    {id:487,departamento_id:11,ciudad:'CARMEN DE CARUPA'},
    {id:488,departamento_id:11,ciudad:'CHAGUANI'},
    {id:489,departamento_id:11,ciudad:'CHIA'},
    {id:490,departamento_id:11,ciudad:'CHIPAQUE'},
    {id:491,departamento_id:11,ciudad:'CHOACHI'},
    {id:492,departamento_id:11,ciudad:'CHOCONTA'},
    {id:493,departamento_id:11,ciudad:'COGUA'},
    {id:494,departamento_id:11,ciudad:'COTA'},
    {id:495,departamento_id:11,ciudad:'CUCUNUBA'},
    {id:496,departamento_id:11,ciudad:'EL COLEGIO'},
    {id:497,departamento_id:11,ciudad:'EL PEÑON'},
    {id:498,departamento_id:11,ciudad:'EL ROSAL'},
    {id:499,departamento_id:11,ciudad:'FACATATIVA'},
    {id:500,departamento_id:11,ciudad:'FOMEQUE'},
    {id:501,departamento_id:11,ciudad:'FOSCA'},
    {id:502,departamento_id:11,ciudad:'FUNZA'},
    {id:503,departamento_id:11,ciudad:'FUQUENE'},
    {id:504,departamento_id:11,ciudad:'FUSAGASUGA'},
    {id:505,departamento_id:11,ciudad:'GACHALA'},
    {id:506,departamento_id:11,ciudad:'GACHANCIPA'},
    {id:507,departamento_id:11,ciudad:'GACHETA'},
    {id:508,departamento_id:11,ciudad:'GAMA'},
    {id:509,departamento_id:11,ciudad:'GIRARDOT'},
    {id:510,departamento_id:11,ciudad:'GRANADA'},
    {id:511,departamento_id:11,ciudad:'GUACHETA'},
    {id:512,departamento_id:11,ciudad:'GUADUAS'},
    {id:513,departamento_id:11,ciudad:'GUASCA'},
    {id:514,departamento_id:11,ciudad:'GUATAQUI'},
    {id:515,departamento_id:11,ciudad:'GUATAVITA'},
    {id:516,departamento_id:11,ciudad:'GUAYABAL DE SIQUIMA'},
    {id:517,departamento_id:11,ciudad:'GUAYABETAL'},
    {id:518,departamento_id:11,ciudad:'GUTIERREZ'},
    {id:519,departamento_id:11,ciudad:'JERUSALEN'},
    {id:520,departamento_id:11,ciudad:'JUNIN'},
    {id:521,departamento_id:11,ciudad:'LA CALERA'},
    {id:522,departamento_id:11,ciudad:'LA MESA'},
    {id:523,departamento_id:11,ciudad:'LA PALMA'},
    {id:524,departamento_id:11,ciudad:'LA PEÑA'},
    {id:525,departamento_id:11,ciudad:'LA VEGA'},
    {id:526,departamento_id:11,ciudad:'LENGUAZAQUE'},
    {id:527,departamento_id:11,ciudad:'MACHETA'},
    {id:528,departamento_id:11,ciudad:'MADRID'},
    {id:529,departamento_id:11,ciudad:'MANTA'},
    {id:530,departamento_id:11,ciudad:'MEDINA'},
    {id:531,departamento_id:11,ciudad:'MOSQUERA'},
    {id:532,departamento_id:11,ciudad:'NARIÑO'},
    {id:533,departamento_id:11,ciudad:'NEMOCON'},
    {id:534,departamento_id:11,ciudad:'NILO'},
    {id:535,departamento_id:11,ciudad:'NIMAIMA'},
    {id:536,departamento_id:11,ciudad:'NOCAIMA'},
    {id:537,departamento_id:11,ciudad:'VENECIA (OSPINA PEREZ'},
    {id:538,departamento_id:11,ciudad:'PACHO'},
    {id:539,departamento_id:11,ciudad:'PAIME'},
    {id:540,departamento_id:11,ciudad:'PANDI'},
    {id:541,departamento_id:11,ciudad:'PARATEBUENO'},
    {id:542,departamento_id:11,ciudad:'PASCA'},
    {id:543,departamento_id:11,ciudad:'PUERTO SALGAR'},
    {id:544,departamento_id:11,ciudad:'PULI'},
    {id:545,departamento_id:11,ciudad:'QUEBRADANEGRA'},
    {id:546,departamento_id:11,ciudad:'QUETAME'},
    {id:547,departamento_id:11,ciudad:'QUIPILE'},
    {id:548,departamento_id:11,ciudad:'APULO (RAFAEL REYES'},
    {id:549,departamento_id:11,ciudad:'RICAURTE'},
    {id:550,departamento_id:11,ciudad:'SAN ANTONIO DEL TEQUENDAMA'},
    {id:551,departamento_id:11,ciudad:'SAN BERNARDO'},
    {id:552,departamento_id:11,ciudad:'SAN CAYETANO'},
    {id:553,departamento_id:11,ciudad:'SAN FRANCISCO'},
    {id:554,departamento_id:11,ciudad:'SAN JUAN DE RIOSECO'},
    {id:555,departamento_id:11,ciudad:'SASAIMA'},
    {id:556,departamento_id:11,ciudad:'SESQUILE'},
    {id:557,departamento_id:11,ciudad:'SIBATE'},
    {id:558,departamento_id:11,ciudad:'SILVANIA'},
    {id:559,departamento_id:11,ciudad:'SIMIJACA'},
    {id:560,departamento_id:11,ciudad:'SOACHA'},
    {id:561,departamento_id:11,ciudad:'SOPO'},
    {id:562,departamento_id:11,ciudad:'SUBACHOQUE'},
    {id:563,departamento_id:11,ciudad:'SUESCA'},
    {id:564,departamento_id:11,ciudad:'SUPATA'},
    {id:565,departamento_id:11,ciudad:'SUSA'},
    {id:566,departamento_id:11,ciudad:'SUTATAUSA'},
    {id:567,departamento_id:11,ciudad:'TABIO'},
    {id:568,departamento_id:11,ciudad:'TAUSA'},
    {id:569,departamento_id:11,ciudad:'TENA'},
    {id:570,departamento_id:11,ciudad:'TENJO'},
    {id:571,departamento_id:11,ciudad:'TIBACUY'},
    {id:572,departamento_id:11,ciudad:'TIBIRITA'},
    {id:573,departamento_id:11,ciudad:'TOCAIMA'},
    {id:574,departamento_id:11,ciudad:'TOCANCIPA'},
    {id:575,departamento_id:11,ciudad:'TOPAIPI'},
    {id:576,departamento_id:11,ciudad:'UBALA'},
    {id:577,departamento_id:11,ciudad:'UBAQUE'},
    {id:578,departamento_id:11,ciudad:'UBATE'},
    {id:579,departamento_id:11,ciudad:'UNE'},
    {id:580,departamento_id:11,ciudad:'UTICA'},
    {id:581,departamento_id:11,ciudad:'VERGARA'},
    {id:582,departamento_id:11,ciudad:'VIANI'},
    {id:583,departamento_id:11,ciudad:'VILLAGOMEZ'},
    {id:584,departamento_id:11,ciudad:'VILLAPINZON'},
    {id:585,departamento_id:11,ciudad:'VILLETA'},
    {id:586,departamento_id:11,ciudad:'VIOTA'},
    {id:587,departamento_id:11,ciudad:'YACOPI'},
    {id:588,departamento_id:11,ciudad:'ZIPACON'},
    {id:589,departamento_id:11,ciudad:'ZIPAQUIRA'},
    {id:590,departamento_id:12,ciudad:'QUIBDO (SAN FRANCISCO DE QUIBDO'},
    {id:591,departamento_id:12,ciudad:'ACANDI'},
    {id:592,departamento_id:12,ciudad:'ALTO BAUDO (PIE DE PATO'},
    {id:593,departamento_id:12,ciudad:'ATRATO'},
    {id:594,departamento_id:12,ciudad:'BAGADO'},
    {id:595,departamento_id:12,ciudad:'BAHIA SOLANO (MUTIS'},
    {id:596,departamento_id:12,ciudad:'BAJO BAUDO (PIZARRO'},
    {id:597,departamento_id:12,ciudad:'BOJAYA (BELLAVISTA'},
    {id:598,departamento_id:12,ciudad:'CANTON DE SAN PABLO (MANAGRU'},
    {id:599,departamento_id:12,ciudad:'CONDOTO'},
    {id:600,departamento_id:12,ciudad:'EL CARMEN DE ATRATO'},
    {id:601,departamento_id:12,ciudad:'LITORAL DEL BAJO SAN JUAN (SANTA GENOVEVA DE DOCORDO'},
    {id:602,departamento_id:12,ciudad:'ISTMINA'},
    {id:603,departamento_id:12,ciudad:'JURADO'},
    {id:604,departamento_id:12,ciudad:'LLORO'},
    {id:605,departamento_id:12,ciudad:'MEDIO ATRATO'},
    {id:606,departamento_id:12,ciudad:'MEDIO BAUDO'},
    {id:607,departamento_id:12,ciudad:'NOVITA'},
    {id:608,departamento_id:12,ciudad:'NUQUI'},
    {id:609,departamento_id:12,ciudad:'RIOQUITO'},
    {id:610,departamento_id:12,ciudad:'RIOSUCIO'},
    {id:611,departamento_id:12,ciudad:'SAN JOSE DEL PALMAR'},
    {id:612,departamento_id:12,ciudad:'SIPI'},
    {id:613,departamento_id:12,ciudad:'TADO'},
    {id:614,departamento_id:12,ciudad:'UNGUIA'},
    {id:615,departamento_id:12,ciudad:'UNION PANAMERICANA'},
    {id:616,departamento_id:13,ciudad:'NEIVA'},
    {id:617,departamento_id:13,ciudad:'ACEVEDO'},
    {id:618,departamento_id:13,ciudad:'AGRADO'},
    {id:619,departamento_id:13,ciudad:'AIPE'},
    {id:620,departamento_id:13,ciudad:'ALGECIRAS'},
    {id:621,departamento_id:13,ciudad:'ALTAMIRA'},
    {id:622,departamento_id:13,ciudad:'BARAYA'},
    {id:623,departamento_id:13,ciudad:'CAMPOALEGRE'},
    {id:624,departamento_id:13,ciudad:'COLOMBIA'},
    {id:625,departamento_id:13,ciudad:'ELIAS'},
    {id:626,departamento_id:13,ciudad:'GARZON'},
    {id:627,departamento_id:13,ciudad:'GIGANTE'},
    {id:628,departamento_id:13,ciudad:'GUADALUPE'},
    {id:629,departamento_id:13,ciudad:'HOBO'},
    {id:630,departamento_id:13,ciudad:'IQUIRA'},
    {id:631,departamento_id:13,ciudad:'ISNOS (SAN JOSE DE ISNOS'},
    {id:632,departamento_id:13,ciudad:'LA ARGENTINA'},
    {id:633,departamento_id:13,ciudad:'LA PLATA'},
    {id:634,departamento_id:13,ciudad:'NATAGA'},
    {id:635,departamento_id:13,ciudad:'OPORAPA'},
    {id:636,departamento_id:13,ciudad:'PAICOL'},
    {id:637,departamento_id:13,ciudad:'PALERMO'},
    {id:638,departamento_id:13,ciudad:'PALESTINA'},
    {id:639,departamento_id:13,ciudad:'PITAL'},
    {id:640,departamento_id:13,ciudad:'PITALITO'},
    {id:641,departamento_id:13,ciudad:'RIVERA'},
    {id:642,departamento_id:13,ciudad:'SALADOBLANCO'},
    {id:643,departamento_id:13,ciudad:'SAN AGUSTIN'},
    {id:644,departamento_id:13,ciudad:'SANTA MARIA'},
    {id:645,departamento_id:13,ciudad:'SUAZA'},
    {id:646,departamento_id:13,ciudad:'TARQUI'},
    {id:647,departamento_id:13,ciudad:'TESALIA'},
    {id:648,departamento_id:13,ciudad:'TELLO'},
    {id:649,departamento_id:13,ciudad:'TERUEL'},
    {id:650,departamento_id:13,ciudad:'TIMANA'},
    {id:651,departamento_id:13,ciudad:'VILLAVIEJA'},
    {id:652,departamento_id:13,ciudad:'YAGUARA'},
    {id:653,departamento_id:14,ciudad:'RIOHACHA'},
    {id:654,departamento_id:14,ciudad:'BARRANCAS'},
    {id:655,departamento_id:14,ciudad:'DIBULLA'},
    {id:656,departamento_id:14,ciudad:'DISTRACCION'},
    {id:657,departamento_id:14,ciudad:'EL MOLINO'},
    {id:658,departamento_id:14,ciudad:'FONSECA'},
    {id:659,departamento_id:14,ciudad:'HATONUEVO'},
    {id:660,departamento_id:14,ciudad:'LA JAGUA DEL PILAR'},
    {id:661,departamento_id:14,ciudad:'MAICAO'},
    {id:662,departamento_id:14,ciudad:'MANAURE'},
    {id:663,departamento_id:14,ciudad:'SAN JUAN DEL CESAR'},
    {id:664,departamento_id:14,ciudad:'URIBIA'},
    {id:665,departamento_id:14,ciudad:'URUMITA'},
    {id:666,departamento_id:14,ciudad:'VILLANUEVA'},
    {id:667,departamento_id:15,ciudad:'SANTA MARTA (DISTRITO TURISTICO CULTURAL E HISTORICO DE SANTA MARTA'},
    {id:668,departamento_id:15,ciudad:'ALGARROBO'},
    {id:669,departamento_id:15,ciudad:'ARACATACA'},
    {id:670,departamento_id:15,ciudad:'ARIGUANI (EL DIFICIL'},
    {id:671,departamento_id:15,ciudad:'CERRO SAN ANTONIO'},
    {id:672,departamento_id:15,ciudad:'CHIVOLO'},
    {id:673,departamento_id:15,ciudad:'CIENAGA'},
    {id:674,departamento_id:15,ciudad:'CONCORDIA'},
    {id:675,departamento_id:15,ciudad:'EL BANCO'},
    {id:676,departamento_id:15,ciudad:'EL PIÑON'},
    {id:677,departamento_id:15,ciudad:'EL RETEN'},
    {id:678,departamento_id:15,ciudad:'FUNDACION'},
    {id:679,departamento_id:15,ciudad:'GUAMAL'},
    {id:680,departamento_id:15,ciudad:'PEDRAZA'},
    {id:681,departamento_id:15,ciudad:'PIJIÑO DEL CARMEN (PIJIÑO'},
    {id:682,departamento_id:15,ciudad:'PIVIJAY'},
    {id:683,departamento_id:15,ciudad:'PLATO'},
    {id:684,departamento_id:15,ciudad:'PUEBLOVIEJO'},
    {id:685,departamento_id:15,ciudad:'REMOLINO'},
    {id:686,departamento_id:15,ciudad:'SABANAS DE SAN ANGEL'},
    {id:687,departamento_id:15,ciudad:'SALAMINA'},
    {id:688,departamento_id:15,ciudad:'SAN SEBASTIAN DE BUENAVISTA'},
    {id:689,departamento_id:15,ciudad:'SAN ZENON'},
    {id:690,departamento_id:15,ciudad:'SANTA ANA'},
    {id:691,departamento_id:15,ciudad:'SITIONUEVO'},
    {id:692,departamento_id:15,ciudad:'TENERIFE'},
    {id:693,departamento_id:16,ciudad:'VILLAVICENCIO'},
    {id:694,departamento_id:16,ciudad:'ACACIAS'},
    {id:695,departamento_id:16,ciudad:'BARRANCA DE UPIA'},
    {id:696,departamento_id:16,ciudad:'CABUYARO'},
    {id:697,departamento_id:16,ciudad:'CASTILLA LA NUEVA'},
    {id:698,departamento_id:16,ciudad:'SAN LUIS DE CUBARRAL'},
    {id:699,departamento_id:16,ciudad:'CUMARAL'},
    {id:700,departamento_id:16,ciudad:'EL CALVARIO'},
    {id:701,departamento_id:16,ciudad:'EL CASTILLO'},
    {id:702,departamento_id:16,ciudad:'EL DORADO'},
    {id:703,departamento_id:16,ciudad:'FUENTE DE ORO'},
    {id:704,departamento_id:16,ciudad:'GRANADA'},
    {id:705,departamento_id:16,ciudad:'GUAMAL'},
    {id:706,departamento_id:16,ciudad:'MAPIRIPAN'},
    {id:707,departamento_id:16,ciudad:'MESETAS'},
    {id:708,departamento_id:16,ciudad:'LA MACARENA'},
    {id:709,departamento_id:16,ciudad:'LA URIBE'},
    {id:710,departamento_id:16,ciudad:'LEJANIAS'},
    {id:711,departamento_id:16,ciudad:'PUERTO CONCORDIA'},
    {id:712,departamento_id:16,ciudad:'PUERTO GAITAN'},
    {id:713,departamento_id:16,ciudad:'PUERTO LOPEZ'},
    {id:714,departamento_id:16,ciudad:'PUERTO LLERAS'},
    {id:715,departamento_id:16,ciudad:'PUERTO RICO'},
    {id:716,departamento_id:16,ciudad:'RESTREPO'},
    {id:717,departamento_id:16,ciudad:'SAN CARLOS DE GUAROA'},
    {id:718,departamento_id:16,ciudad:'SAN JUAN DE ARAMA'},
    {id:719,departamento_id:16,ciudad:'SAN JUANITO'},
    {id:720,departamento_id:16,ciudad:'SAN MARTIN'},
    {id:721,departamento_id:16,ciudad:'VISTAHERMOSA'},
    {id:722,departamento_id:17,ciudad:'PASTO (SAN JUAN DE PASTO'},
    {id:723,departamento_id:17,ciudad:'ALBAN (SAN JOSE'},
    {id:724,departamento_id:17,ciudad:'ALDANA'},
    {id:725,departamento_id:17,ciudad:'ANCUYA'},
    {id:726,departamento_id:17,ciudad:'ARBOLEDA (BERRUECOS'},
    {id:727,departamento_id:17,ciudad:'BARBACOAS'},
    {id:728,departamento_id:17,ciudad:'BELEN'},
    {id:729,departamento_id:17,ciudad:'BUESACO'},
    {id:730,departamento_id:17,ciudad:'COLON (GENOVA'},
    {id:731,departamento_id:17,ciudad:'CONSACA'},
    {id:732,departamento_id:17,ciudad:'CONTADERO'},
    {id:733,departamento_id:17,ciudad:'CORDOBA'},
    {id:734,departamento_id:17,ciudad:'CUASPUD (CARLOSAMA'},
    {id:735,departamento_id:17,ciudad:'CUMBAL'},
    {id:736,departamento_id:17,ciudad:'CUMBITARA'},
    {id:737,departamento_id:17,ciudad:'CHACHAGUI'},
    {id:738,departamento_id:17,ciudad:'EL CHARCO'},
    {id:739,departamento_id:17,ciudad:'EL PEÑOL'},
    {id:740,departamento_id:17,ciudad:'EL ROSARIO'},
    {id:741,departamento_id:17,ciudad:'EL TABLON'},
    {id:742,departamento_id:17,ciudad:'EL TAMBO'},
    {id:743,departamento_id:17,ciudad:'FUNES'},
    {id:744,departamento_id:17,ciudad:'GUACHUCAL'},
    {id:745,departamento_id:17,ciudad:'GUAITARILLA'},
    {id:746,departamento_id:17,ciudad:'GUALMATAN'},
    {id:747,departamento_id:17,ciudad:'ILES'},
    {id:748,departamento_id:17,ciudad:'IMUES'},
    {id:749,departamento_id:17,ciudad:'IPIALES'},
    {id:750,departamento_id:17,ciudad:'LA CRUZ'},
    {id:751,departamento_id:17,ciudad:'LA FLORIDA'},
    {id:752,departamento_id:17,ciudad:'LA LLANADA'},
    {id:753,departamento_id:17,ciudad:'LA TOLA'},
    {id:754,departamento_id:17,ciudad:'LA UNION'},
    {id:755,departamento_id:17,ciudad:'LEIVA'},
    {id:756,departamento_id:17,ciudad:'LINARES'},
    {id:757,departamento_id:17,ciudad:'LOS ANDES (SOTOMAYOR'},
    {id:758,departamento_id:17,ciudad:'MAGUI (PAYAN'},
    {id:759,departamento_id:17,ciudad:'MALLAMA (PIEDRANCHA'},
    {id:760,departamento_id:17,ciudad:'MOSQUERA'},
    {id:761,departamento_id:17,ciudad:'OLAYA HERRERA (BOCAS DE SATINGA'},
    {id:762,departamento_id:17,ciudad:'OSPINA'},
    {id:763,departamento_id:17,ciudad:'FRANCISCO PIZARRO (SALAHONDA'},
    {id:764,departamento_id:17,ciudad:'POLICARPA'},
    {id:765,departamento_id:17,ciudad:'POTOSI'},
    {id:766,departamento_id:17,ciudad:'PROVIDENCIA'},
    {id:767,departamento_id:17,ciudad:'PUERRES'},
    {id:768,departamento_id:17,ciudad:'PUPIALES'},
    {id:769,departamento_id:17,ciudad:'RICAURTE'},
    {id:770,departamento_id:17,ciudad:'ROBERTO PAYAN (SAN JOSE'},
    {id:771,departamento_id:17,ciudad:'SAMANIEGO'},
    {id:772,departamento_id:17,ciudad:'SANDONA'},
    {id:773,departamento_id:17,ciudad:'SAN BERNARDO'},
    {id:774,departamento_id:17,ciudad:'SAN LORENZO'},
    {id:775,departamento_id:17,ciudad:'SAN PABLO'},
    {id:776,departamento_id:17,ciudad:'SAN PEDRO DE CARTAGO'},
    {id:777,departamento_id:17,ciudad:'SANTA BARBARA (ISCUANDE'},
    {id:778,departamento_id:17,ciudad:'SANTA CRUZ (GUACHAVES'},
    {id:779,departamento_id:17,ciudad:'SAPUYES'},
    {id:780,departamento_id:17,ciudad:'TAMINANGO'},
    {id:781,departamento_id:17,ciudad:'TANGUA'},
    {id:782,departamento_id:17,ciudad:'TUMACO'},
    {id:783,departamento_id:17,ciudad:'TUQUERRES'},
    {id:784,departamento_id:17,ciudad:'YACUANQUER'},
    {id:785,departamento_id:18,ciudad:'CUCUTA'},
    {id:786,departamento_id:18,ciudad:'ABREGO'},
    {id:787,departamento_id:18,ciudad:'ARBOLEDAS'},
    {id:788,departamento_id:18,ciudad:'BOCHALEMA'},
    {id:789,departamento_id:18,ciudad:'BUCARASICA'},
    {id:790,departamento_id:18,ciudad:'CACOTA'},
    {id:791,departamento_id:18,ciudad:'CACHIRA'},
    {id:792,departamento_id:18,ciudad:'CHINACOTA'},
    {id:793,departamento_id:18,ciudad:'CHITAGA'},
    {id:794,departamento_id:18,ciudad:'CONVENCION'},
    {id:795,departamento_id:18,ciudad:'CUCUTILLA'},
    {id:796,departamento_id:18,ciudad:'DURANIA'},
    {id:797,departamento_id:18,ciudad:'EL CARMEN'},
    {id:798,departamento_id:18,ciudad:'EL TARRA'},
    {id:799,departamento_id:18,ciudad:'EL ZULIA'},
    {id:800,departamento_id:18,ciudad:'GRAMALOTE'},
    {id:801,departamento_id:18,ciudad:'HACARI'},
    {id:802,departamento_id:18,ciudad:'HERRAN'},
    {id:803,departamento_id:18,ciudad:'LABATECA'},
    {id:804,departamento_id:18,ciudad:'LA ESPERANZA'},
    {id:805,departamento_id:18,ciudad:'LA PLAYA'},
    {id:806,departamento_id:18,ciudad:'LOS PATIOS'},
    {id:807,departamento_id:18,ciudad:'LOURDES'},
    {id:808,departamento_id:18,ciudad:'MUTISCUA'},
    {id:809,departamento_id:18,ciudad:'OCAÑA'},
    {id:810,departamento_id:18,ciudad:'PAMPLONA'},
    {id:811,departamento_id:18,ciudad:'PAMPLONITA'},
    {id:812,departamento_id:18,ciudad:'PUERTO SANTANDER'},
    {id:813,departamento_id:18,ciudad:'RAGONVALIA'},
    {id:814,departamento_id:18,ciudad:'SALAZAR'},
    {id:815,departamento_id:18,ciudad:'SAN CALIXTO'},
    {id:816,departamento_id:18,ciudad:'SAN CAYETANO'},
    {id:817,departamento_id:18,ciudad:'SANTIAGO'},
    {id:818,departamento_id:18,ciudad:'SARDINATA'},
    {id:819,departamento_id:18,ciudad:'SILOS'},
    {id:820,departamento_id:18,ciudad:'TEORAMA'},
    {id:821,departamento_id:18,ciudad:'TIBU'},
    {id:822,departamento_id:18,ciudad:'TOLEDO'},
    {id:823,departamento_id:18,ciudad:'VILLACARO'},
    {id:824,departamento_id:18,ciudad:'VILLA DEL ROSARIO'},
    {id:825,departamento_id:19,ciudad:'ARMENIA'},
    {id:826,departamento_id:19,ciudad:'BUENAVISTA'},
    {id:827,departamento_id:19,ciudad:'CALARCA'},
    {id:828,departamento_id:19,ciudad:'CIRCASIA'},
    {id:829,departamento_id:19,ciudad:'CORDOBA'},
    {id:830,departamento_id:19,ciudad:'FILANDIA'},
    {id:831,departamento_id:19,ciudad:'GENOVA'},
    {id:832,departamento_id:19,ciudad:'LA TEBAIDA'},
    {id:833,departamento_id:19,ciudad:'MONTENEGRO'},
    {id:834,departamento_id:19,ciudad:'PIJAO'},
    {id:835,departamento_id:19,ciudad:'QUIMBAYA'},
    {id:836,departamento_id:19,ciudad:'SALENTO'},
    {id:837,departamento_id:20,ciudad:'PEREIRA'},
    {id:838,departamento_id:20,ciudad:'APIA'},
    {id:839,departamento_id:20,ciudad:'BALBOA'},
    {id:840,departamento_id:20,ciudad:'BELEN DE UMBRIA'},
    {id:841,departamento_id:20,ciudad:'DOS QUEBRADAS'},
    {id:842,departamento_id:20,ciudad:'GUATICA'},
    {id:843,departamento_id:20,ciudad:'LA CELIA'},
    {id:844,departamento_id:20,ciudad:'LA VIRGINIA'},
    {id:845,departamento_id:20,ciudad:'MARSELLA'},
    {id:846,departamento_id:20,ciudad:'MISTRATO'},
    {id:847,departamento_id:20,ciudad:'PUEBLO RICO'},
    {id:848,departamento_id:20,ciudad:'QUINCHIA'},
    {id:849,departamento_id:20,ciudad:'SANTA ROSA DE CABAL'},
    {id:850,departamento_id:20,ciudad:'SANTUARIO'},
    {id:851,departamento_id:21,ciudad:'BUCARAMANGA'},
    {id:852,departamento_id:21,ciudad:'AGUADA'},
    {id:853,departamento_id:21,ciudad:'ALBANIA'},
    {id:854,departamento_id:21,ciudad:'ARATOCA'},
    {id:855,departamento_id:21,ciudad:'BARBOSA'},
    {id:856,departamento_id:21,ciudad:'BARICHARA'},
    {id:857,departamento_id:21,ciudad:'BARRANCABERMEJA'},
    {id:858,departamento_id:21,ciudad:'BETULIA'},
    {id:859,departamento_id:21,ciudad:'BOLIVAR'},
    {id:860,departamento_id:21,ciudad:'CABRERA'},
    {id:861,departamento_id:21,ciudad:'CALIFORNIA'},
    {id:862,departamento_id:21,ciudad:'CAPITANEJO'},
    {id:863,departamento_id:21,ciudad:'CARCASI'},
    {id:864,departamento_id:21,ciudad:'CEPITA'},
    {id:865,departamento_id:21,ciudad:'CERRITO'},
    {id:866,departamento_id:21,ciudad:'CHARALA'},
    {id:867,departamento_id:21,ciudad:'CHARTA'},
    {id:868,departamento_id:21,ciudad:'CHIMA'},
    {id:869,departamento_id:21,ciudad:'CHIPATA'},
    {id:870,departamento_id:21,ciudad:'CIMITARRA'},
    {id:871,departamento_id:21,ciudad:'CONCEPCION'},
    {id:872,departamento_id:21,ciudad:'CONFINES'},
    {id:873,departamento_id:21,ciudad:'CONTRATACION'},
    {id:874,departamento_id:21,ciudad:'COROMORO'},
    {id:875,departamento_id:21,ciudad:'CURITI'},
    {id:876,departamento_id:21,ciudad:'EL CARMEN DE CHUCURY'},
    {id:877,departamento_id:21,ciudad:'EL GUACAMAYO'},
    {id:878,departamento_id:21,ciudad:'EL PEÑON'},
    {id:879,departamento_id:21,ciudad:'EL PLAYON'},
    {id:880,departamento_id:21,ciudad:'ENCINO'},
    {id:881,departamento_id:21,ciudad:'ENCISO'},
    {id:882,departamento_id:21,ciudad:'FLORIAN'},
    {id:883,departamento_id:21,ciudad:'FLORIDABLANCA'},
    {id:884,departamento_id:21,ciudad:'GALAN'},
    {id:885,departamento_id:21,ciudad:'GAMBITA'},
    {id:886,departamento_id:21,ciudad:'GIRON'},
    {id:887,departamento_id:21,ciudad:'GUACA'},
    {id:888,departamento_id:21,ciudad:'GUADALUPE'},
    {id:889,departamento_id:21,ciudad:'GUAPOTA'},
    {id:890,departamento_id:21,ciudad:'GUAVATA'},
    {id:891,departamento_id:21,ciudad:'GUEPSA'},
    {id:892,departamento_id:21,ciudad:'HATO'},
    {id:893,departamento_id:21,ciudad:'JESUS MARIA'},
    {id:894,departamento_id:21,ciudad:'JORDAN'},
    {id:895,departamento_id:21,ciudad:'LA BELLEZA'},
    {id:896,departamento_id:21,ciudad:'LANDAZURI'},
    {id:897,departamento_id:21,ciudad:'LA PAZ'},
    {id:898,departamento_id:21,ciudad:'LEBRIJA'},
    {id:899,departamento_id:21,ciudad:'LOS SANTOS'},
    {id:900,departamento_id:21,ciudad:'MACARAVITA'},
    {id:901,departamento_id:21,ciudad:'MALAGA'},
    {id:902,departamento_id:21,ciudad:'MATANZA'},
    {id:903,departamento_id:21,ciudad:'MOGOTES'},
    {id:904,departamento_id:21,ciudad:'MOLAGAVITA'},
    {id:905,departamento_id:21,ciudad:'OCAMONTE'},
    {id:906,departamento_id:21,ciudad:'OIBA'},
    {id:907,departamento_id:21,ciudad:'ONZAGA'},
    {id:908,departamento_id:21,ciudad:'PALMAR'},
    {id:909,departamento_id:21,ciudad:'PALMAS DEL SOCORRO'},
    {id:910,departamento_id:21,ciudad:'PARAMO'},
    {id:911,departamento_id:21,ciudad:'PIEDECUESTA'},
    {id:912,departamento_id:21,ciudad:'PINCHOTE'},
    {id:913,departamento_id:21,ciudad:'PUENTE NACIONAL'},
    {id:914,departamento_id:21,ciudad:'PUERTO PARRA'},
    {id:915,departamento_id:21,ciudad:'PUERTO WILCHES'},
    {id:916,departamento_id:21,ciudad:'RIONEGRO'},
    {id:917,departamento_id:21,ciudad:'SABANA DE TORRES'},
    {id:918,departamento_id:21,ciudad:'SAN ANDRES'},
    {id:919,departamento_id:21,ciudad:'SAN BENITO'},
    {id:920,departamento_id:21,ciudad:'SAN GIL'},
    {id:921,departamento_id:21,ciudad:'SAN JOAQUIN'},
    {id:922,departamento_id:21,ciudad:'SAN JOSE DE MIRANDA'},
    {id:923,departamento_id:21,ciudad:'SAN MIGUEL'},
    {id:924,departamento_id:21,ciudad:'SAN VICENTE DE CHUCURI'},
    {id:925,departamento_id:21,ciudad:'SANTA BARBARA'},
    {id:926,departamento_id:21,ciudad:'SANTA HELENA DEL OPON'},
    {id:927,departamento_id:21,ciudad:'SIMACOTA'},
    {id:928,departamento_id:21,ciudad:'SOCORRO'},
    {id:929,departamento_id:21,ciudad:'SUAITA'},
    {id:930,departamento_id:21,ciudad:'SUCRE'},
    {id:931,departamento_id:21,ciudad:'SURATA'},
    {id:932,departamento_id:21,ciudad:'TONA'},
    {id:933,departamento_id:21,ciudad:'VALLE SAN JOSE'},
    {id:934,departamento_id:21,ciudad:'VELEZ'},
    {id:935,departamento_id:21,ciudad:'VETAS'},
    {id:936,departamento_id:21,ciudad:'VILLANUEVA'},
    {id:937,departamento_id:21,ciudad:'ZAPATOCA'},
    {id:938,departamento_id:22,ciudad:'SINCELEJO'},
    {id:939,departamento_id:22,ciudad:'BUENAVISTA'},
    {id:940,departamento_id:22,ciudad:'CAIMITO'},
    {id:941,departamento_id:22,ciudad:'COLOSO (RICAURTE'},
    {id:942,departamento_id:22,ciudad:'COROZAL'},
    {id:943,departamento_id:22,ciudad:'CHALAN'},
    {id:944,departamento_id:22,ciudad:'GALERAS (NUEVA GRANADA'},
    {id:945,departamento_id:22,ciudad:'GUARANDA'},
    {id:946,departamento_id:22,ciudad:'LA UNION'},
    {id:947,departamento_id:22,ciudad:'LOS PALMITOS'},
    {id:948,departamento_id:22,ciudad:'MAJAGUAL'},
    {id:949,departamento_id:22,ciudad:'MORROA'},
    {id:950,departamento_id:22,ciudad:'OVEJAS'},
    {id:951,departamento_id:22,ciudad:'PALMITO'},
    {id:952,departamento_id:22,ciudad:'SAMPUES'},
    {id:953,departamento_id:22,ciudad:'SAN BENITO ABAD'},
    {id:954,departamento_id:22,ciudad:'SAN JUAN DE BETULIA'},
    {id:955,departamento_id:22,ciudad:'SAN MARCOS'},
    {id:956,departamento_id:22,ciudad:'SAN ONOFRE'},
    {id:957,departamento_id:22,ciudad:'SAN PEDRO'},
    {id:958,departamento_id:22,ciudad:'SINCE'},
    {id:959,departamento_id:22,ciudad:'SUCRE'},
    {id:960,departamento_id:22,ciudad:'TOLU'},
    {id:961,departamento_id:22,ciudad:'TOLUVIEJO'},
    {id:962,departamento_id:23,ciudad:'IBAGUE'},
    {id:963,departamento_id:23,ciudad:'ALPUJARRA'},
    {id:964,departamento_id:23,ciudad:'ALVARADO'},
    {id:965,departamento_id:23,ciudad:'AMBALEMA'},
    {id:966,departamento_id:23,ciudad:'ANZOATEGUI'},
    {id:967,departamento_id:23,ciudad:'ARMERO (GUAYABAL'},
    {id:968,departamento_id:23,ciudad:'ATACO'},
    {id:969,departamento_id:23,ciudad:'CAJAMARCA'},
    {id:970,departamento_id:23,ciudad:'CARMEN APICALA'},
    {id:971,departamento_id:23,ciudad:'CASABIANCA'},
    {id:972,departamento_id:23,ciudad:'CHAPARRAL'},
    {id:973,departamento_id:23,ciudad:'COELLO'},
    {id:974,departamento_id:23,ciudad:'COYAIMA'},
    {id:975,departamento_id:23,ciudad:'CUNDAY'},
    {id:976,departamento_id:23,ciudad:'DOLORES'},
    {id:977,departamento_id:23,ciudad:'ESPINAL'},
    {id:978,departamento_id:23,ciudad:'FALAN'},
    {id:979,departamento_id:23,ciudad:'FLANDES'},
    {id:980,departamento_id:23,ciudad:'FRESNO'},
    {id:981,departamento_id:23,ciudad:'GUAMO'},
    {id:982,departamento_id:23,ciudad:'HERVEO'},
    {id:983,departamento_id:23,ciudad:'HONDA'},
    {id:984,departamento_id:23,ciudad:'ICONONZO'},
    {id:985,departamento_id:23,ciudad:'LERIDA'},
    {id:986,departamento_id:23,ciudad:'LIBANO'},
    {id:987,departamento_id:23,ciudad:'MARIQUITA'},
    {id:988,departamento_id:23,ciudad:'MELGAR'},
    {id:989,departamento_id:23,ciudad:'MURILLO'},
    {id:990,departamento_id:23,ciudad:'NATAGAIMA'},
    {id:991,departamento_id:23,ciudad:'ORTEGA'},
    {id:992,departamento_id:23,ciudad:'PALOCABILDO'},
    {id:993,departamento_id:23,ciudad:'PIEDRAS'},
    {id:994,departamento_id:23,ciudad:'PLANADAS'},
    {id:995,departamento_id:23,ciudad:'PRADO'},
    {id:996,departamento_id:23,ciudad:'PURIFICACION'},
    {id:997,departamento_id:23,ciudad:'RIOBLANCO'},
    {id:998,departamento_id:23,ciudad:'RONCESVALLES'},
    {id:999,departamento_id:23,ciudad:'ROVIRA'},
    {id:1000,departamento_id:23,ciudad:'SALDAÑA'},
    {id:1001,departamento_id:23,ciudad:'SAN ANTONIO'},
    {id:1002,departamento_id:23,ciudad:'SAN LUIS'},
    {id:1003,departamento_id:23,ciudad:'SANTA ISABEL'},
    {id:1004,departamento_id:23,ciudad:'SUAREZ'},
    {id:1005,departamento_id:23,ciudad:'VALLE DE SAN JUAN'},
    {id:1006,departamento_id:23,ciudad:'VENADILLO'},
    {id:1007,departamento_id:23,ciudad:'VILLAHERMOSA'},
    {id:1008,departamento_id:23,ciudad:'VILLARRICA'},
    {id:1009,departamento_id:24,ciudad:'CALI (SANTIAGO DE CALI'},
    {id:1010,departamento_id:24,ciudad:'ALCALA'},
    {id:1011,departamento_id:24,ciudad:'ANDALUCIA'},
    {id:1012,departamento_id:24,ciudad:'ANSERMANUEVO'},
    {id:1013,departamento_id:24,ciudad:'ARGELIA'},
    {id:1014,departamento_id:24,ciudad:'BOLIVAR'},
    {id:1015,departamento_id:24,ciudad:'BUENAVENTURA'},
    {id:1016,departamento_id:24,ciudad:'BUGA'},
    {id:1017,departamento_id:24,ciudad:'BUGALAGRANDE'},
    {id:1018,departamento_id:24,ciudad:'CAICEDONIA'},
    {id:1019,departamento_id:24,ciudad:'CALIMA (DARIEN'},
    {id:1020,departamento_id:24,ciudad:'CANDELARIA'},
    {id:1021,departamento_id:24,ciudad:'CARTAGO'},
    {id:1022,departamento_id:24,ciudad:'DAGUA'},
    {id:1023,departamento_id:24,ciudad:'EL AGUILA'},
    {id:1024,departamento_id:24,ciudad:'EL CAIRO'},
    {id:1025,departamento_id:24,ciudad:'EL CERRITO'},
    {id:1026,departamento_id:24,ciudad:'EL DOVIO'},
    {id:1027,departamento_id:24,ciudad:'FLORIDA'},
    {id:1028,departamento_id:24,ciudad:'GINEBRA'},
    {id:1029,departamento_id:24,ciudad:'GUACARI'},
    {id:1030,departamento_id:24,ciudad:'JAMUNDI'},
    {id:1031,departamento_id:24,ciudad:'LA CUMBRE'},
    {id:1032,departamento_id:24,ciudad:'LA UNION'},
    {id:1033,departamento_id:24,ciudad:'LA VICTORIA'},
    {id:1034,departamento_id:24,ciudad:'OBANDO'},
    {id:1035,departamento_id:24,ciudad:'PALMIRA'},
    {id:1036,departamento_id:24,ciudad:'PRADERA'},
    {id:1037,departamento_id:24,ciudad:'RESTREPO'},
    {id:1038,departamento_id:24,ciudad:'RIOFRIO'},
    {id:1039,departamento_id:24,ciudad:'ROLDANILLO'},
    {id:1040,departamento_id:24,ciudad:'SAN PEDRO'},
    {id:1041,departamento_id:24,ciudad:'SEVILLA'},
    {id:1042,departamento_id:24,ciudad:'TORO'},
    {id:1043,departamento_id:24,ciudad:'TRUJILLO'},
    {id:1044,departamento_id:24,ciudad:'TULUA'},
    {id:1045,departamento_id:24,ciudad:'ULLOA'},
    {id:1046,departamento_id:24,ciudad:'VERSALLES'},
    {id:1047,departamento_id:24,ciudad:'VIJES'},
    {id:1048,departamento_id:24,ciudad:'YOTOCO'},
    {id:1049,departamento_id:24,ciudad:'YUMBO'},
    {id:1050,departamento_id:24,ciudad:'ZARZAL'},
    {id:1051,departamento_id:25,ciudad:'ARAUCA'},
    {id:1052,departamento_id:25,ciudad:'ARAUQUITA'},
    {id:1053,departamento_id:25,ciudad:'CRAVO NORTE'},
    {id:1054,departamento_id:25,ciudad:'FORTUL'},
    {id:1055,departamento_id:25,ciudad:'PUERTO RONDON'},
    {id:1056,departamento_id:25,ciudad:'SARAVENA'},
    {id:1057,departamento_id:25,ciudad:'TAME'},
    {id:1058,departamento_id:26,ciudad:'YOPAL'},
    {id:1059,departamento_id:26,ciudad:'AGUAZUL'},
    {id:1060,departamento_id:26,ciudad:'CHAMEZA'},
    {id:1061,departamento_id:26,ciudad:'HATO COROZAL'},
    {id:1062,departamento_id:26,ciudad:'LA SALINA'},
    {id:1063,departamento_id:26,ciudad:'MANI'},
    {id:1064,departamento_id:26,ciudad:'MONTERREY'},
    {id:1065,departamento_id:26,ciudad:'NUNCHIA'},
    {id:1066,departamento_id:26,ciudad:'OROCUE'},
    {id:1067,departamento_id:26,ciudad:'PAZ DE ARIPORO'},
    {id:1068,departamento_id:26,ciudad:'PORE'},
    {id:1069,departamento_id:26,ciudad:'RECETOR'},
    {id:1070,departamento_id:26,ciudad:'SABANALARGA'},
    {id:1071,departamento_id:26,ciudad:'SACAMA'},
    {id:1072,departamento_id:26,ciudad:'SAN LUIS DE PALENQUE'},
    {id:1073,departamento_id:26,ciudad:'TAMARA'},
    {id:1074,departamento_id:26,ciudad:'TAURAMENA'},
    {id:1075,departamento_id:26,ciudad:'TRINIDAD'},
    {id:1076,departamento_id:26,ciudad:'VILLANUEVA'},
    {id:1077,departamento_id:27,ciudad:'MOCOA'},
    {id:1078,departamento_id:27,ciudad:'COLON'},
    {id:1079,departamento_id:27,ciudad:'ORITO'},
    {id:1080,departamento_id:27,ciudad:'PUERTO ASIS'},
    {id:1081,departamento_id:27,ciudad:'PUERTO CAICEDO'},
    {id:1082,departamento_id:27,ciudad:'PUERTO GUZMAN'},
    {id:1083,departamento_id:27,ciudad:'PUERTO LEGUIZAMO'},
    {id:1084,departamento_id:27,ciudad:'SIBUNDOY'},
    {id:1085,departamento_id:27,ciudad:'SAN FRANCISCO'},
    {id:1086,departamento_id:27,ciudad:'SAN MIGUEL (LA DORADA'},
    {id:1087,departamento_id:27,ciudad:'SANTIAGO'},
    {id:1088,departamento_id:27,ciudad:'LA HORMIGA (VALLE DEL GUAMUEZ'},
    {id:1089,departamento_id:27,ciudad:'VILLAGARZON'},
    {id:1090,departamento_id:28,ciudad:'SAN ANDRES'},
    {id:1091,departamento_id:28,ciudad:'PROVIDENCIA'},
    {id:1092,departamento_id:29,ciudad:'LETICIA'},
    {id:1093,departamento_id:29,ciudad:'EL ENCANTO'},
    {id:1094,departamento_id:29,ciudad:'LA CHORRERA'},
    {id:1095,departamento_id:29,ciudad:'LA PEDRERA'},
    {id:1096,departamento_id:29,ciudad:'LA VICTORIA'},
    {id:1097,departamento_id:29,ciudad:'MIRITI-PARANA'},
    {id:1098,departamento_id:29,ciudad:'PUERTO ALEGRIA'},
    {id:1099,departamento_id:29,ciudad:'PUERTO ARICA'},
    {id:1100,departamento_id:29,ciudad:'PUERTO NARIÑO'},
    {id:1101,departamento_id:29,ciudad:'PUERTO SANTANDER'},
    {id:1102,departamento_id:29,ciudad:'TARAPACA'},
    {id:1103,departamento_id:30,ciudad:'PUERTO INIRIDA'},
    {id:1104,departamento_id:30,ciudad:'BARRANCO MINAS'},
    {id:1105,departamento_id:30,ciudad:'SAN FELIPE'},
    {id:1106,departamento_id:30,ciudad:'PUERTO COLOMBIA'},
    {id:1107,departamento_id:30,ciudad:'LA GUADALUPE'},
    {id:1108,departamento_id:30,ciudad:'CACAHUAL'},
    {id:1109,departamento_id:30,ciudad:'PANA PANA (CAMPO ALEGRE'},
    {id:1110,departamento_id:30,ciudad:'MORICHAL (MORICHAL NUEVO'},
    {id:1111,departamento_id:31,ciudad:'SAN JOSE DEL GUAVIARE'},
    {id:1112,departamento_id:31,ciudad:'CALAMAR'},
    {id:1113,departamento_id:31,ciudad:'EL RETORNO'},
    {id:1114,departamento_id:31,ciudad:'MIRAFLORES'},
    {id:1115,departamento_id:32,ciudad:'MITU'},
    {id:1116,departamento_id:32,ciudad:'CARURU'},
    {id:1117,departamento_id:32,ciudad:'PACOA'},
    {id:1118,departamento_id:32,ciudad:'TARAIRA'},
    {id:1119,departamento_id:32,ciudad:'PAPUNAUA (MORICHAL'},
    {id:1120,departamento_id:32,ciudad:'YAVARATE'},
    {id:1121,departamento_id:33,ciudad:'PUERTO CARREÑO'},
    {id:1122,departamento_id:33,ciudad:'LA PRIMAVERA'},
    {id:1123,departamento_id:33,ciudad:'SANTA RITA'},
    {id:1124,departamento_id:33,ciudad:'SANTA ROSALIA'},
    {id:1125,departamento_id:33,ciudad:'SAN JOSE DE OCUNE'},
    {id:1126,departamento_id:33,ciudad:'CUMARIBO'},

]
localStorage.setItem('ListaCiudadesCol',JSON.stringify(Ciudades));
return(
    <div></div>
);

}
export default Ciudades;